/*
 * MFS
 * Multi-source File-like Search — HTTP /v1 control plane.
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.zilliz.mfs.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for JobResponse
 */
public class JobResponseTest {
    private final JobResponse model = new JobResponse();

    /**
     * Model tests for JobResponse
     */
    @Test
    public void testJobResponse() {
        // TODO: test JobResponse
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'opKind'
     */
    @Test
    public void opKindTest() {
        // TODO: test opKind
    }

    /**
     * Test the property 'trigger'
     */
    @Test
    public void triggerTest() {
        // TODO: test trigger
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

    /**
     * Test the property 'totalObjects'
     */
    @Test
    public void totalObjectsTest() {
        // TODO: test totalObjects
    }

    /**
     * Test the property 'succeededObjects'
     */
    @Test
    public void succeededObjectsTest() {
        // TODO: test succeededObjects
    }

    /**
     * Test the property 'failedObjects'
     */
    @Test
    public void failedObjectsTest() {
        // TODO: test failedObjects
    }

    /**
     * Test the property 'cancelledObjects'
     */
    @Test
    public void cancelledObjectsTest() {
        // TODO: test cancelledObjects
    }

    /**
     * Test the property 'startedAt'
     */
    @Test
    public void startedAtTest() {
        // TODO: test startedAt
    }

    /**
     * Test the property 'finishedAt'
     */
    @Test
    public void finishedAtTest() {
        // TODO: test finishedAt
    }

}
