/*
 * MFS
 * Multi-source File-like Search — HTTP /v1 control plane.
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.zilliz.mfs.model;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for LocationInner
 */
public class LocationInnerTest {
    private final LocationInner model = new LocationInner();

    /**
     * Model tests for LocationInner
     */
    @Test
    public void testLocationInner() {
        // TODO: test LocationInner
    }

}
