/*
 * MFS
 * Multi-source File-like Search — HTTP /v1 control plane.
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.zilliz.mfs.api;

import io.zilliz.mfs.ApiException;
import io.zilliz.mfs.model.AddRequest;
import io.zilliz.mfs.model.AddResponse;
import io.zilliz.mfs.model.HTTPValidationError;
import io.zilliz.mfs.model.JobResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IngestApi
 */
@Disabled
public class IngestApiTest {

    private final IngestApi api = new IngestApi();

    /**
     * Add
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addSourceTest() throws ApiException {
        AddRequest addRequest = null;
        AddResponse response = api.addSource(addRequest);
        // TODO: test validations
    }

    /**
     * Job
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getJobTest() throws ApiException {
        String jobId = null;
        JobResponse response = api.getJob(jobId);
        // TODO: test validations
    }

}
