/*
 * MFS
 * Multi-source File-like Search — HTTP /v1 control plane.
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.zilliz.mfs.api;

import io.zilliz.mfs.ApiException;
import io.zilliz.mfs.model.GrepResponse;
import io.zilliz.mfs.model.HTTPValidationError;
import io.zilliz.mfs.model.SearchResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RetrievalApi
 */
@Disabled
public class RetrievalApiTest {

    private final RetrievalApi api = new RetrievalApi();

    /**
     * Grep
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void grepTest() throws ApiException {
        String pattern = null;
        String path = null;
        GrepResponse response = api.grep(pattern, path);
        // TODO: test validations
    }

    /**
     * Search
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void searchTest() throws ApiException {
        String q = null;
        String path = null;
        String mode = null;
        Integer topK = null;
        Boolean collapse = null;
        SearchResponse response = api.search(q, path, mode, topK, collapse);
        // TODO: test validations
    }

}
