/*
 * MFS
 * Multi-source File-like Search — HTTP /v1 control plane.
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.zilliz.mfs.api;

import io.zilliz.mfs.ApiException;
import io.zilliz.mfs.model.ServerInfo;
import io.zilliz.mfs.model.StatusResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ServerApi
 */
@Disabled
public class ServerApiTest {

    private final ServerApi api = new ServerApi();

    /**
     * Server Info
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getServerInfoTest() throws ApiException {
        ServerInfo response = api.getServerInfo();
        // TODO: test validations
    }

    /**
     * Status
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void statusTest() throws ApiException {
        StatusResponse response = api.status();
        // TODO: test validations
    }

}
