# coding: utf-8

"""
    MFS

    Multi-source File-like Search — HTTP /v1 control plane.

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mfs_sdk.api.retrieval_api import RetrievalApi


class TestRetrievalApi(unittest.TestCase):
    """RetrievalApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RetrievalApi()

    def tearDown(self) -> None:
        pass

    def test_grep(self) -> None:
        """Test case for grep

        Grep
        """
        pass

    def test_search(self) -> None:
        """Test case for search

        Search
        """
        pass


if __name__ == '__main__':
    unittest.main()
