# coding: utf-8

"""
    MFS

    Multi-source File-like Search — HTTP /v1 control plane.

    The version of the OpenAPI document: 0.4.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mfs_sdk.api.connectors_api import ConnectorsApi


class TestConnectorsApi(unittest.TestCase):
    """ConnectorsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConnectorsApi()

    def tearDown(self) -> None:
        pass

    def test_estimate_connector(self) -> None:
        """Test case for estimate_connector

        Estimate
        """
        pass

    def test_inspect_connector(self) -> None:
        """Test case for inspect_connector

        Inspect
        """
        pass

    def test_probe_connector(self) -> None:
        """Test case for probe_connector

        Probe
        """
        pass

    def test_remove_connector(self) -> None:
        """Test case for remove_connector

        Remove
        """
        pass


if __name__ == '__main__':
    unittest.main()
