# coding: utf-8

"""
    MFS

    Multi-source File-like Search — HTTP /v1 control plane.

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mfs_sdk.api.server_api import ServerApi


class TestServerApi(unittest.TestCase):
    """ServerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServerApi()

    def tearDown(self) -> None:
        pass

    def test_get_server_info(self) -> None:
        """Test case for get_server_info

        Server Info
        """
        pass

    def test_status(self) -> None:
        """Test case for status

        Status
        """
        pass


if __name__ == '__main__':
    unittest.main()
