# coding: utf-8

"""
    MFS

    Multi-source File-like Search — HTTP /v1 control plane.

    The version of the OpenAPI document: 0.4.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mfs_sdk.models.manifest_response import ManifestResponse

class TestManifestResponse(unittest.TestCase):
    """ManifestResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManifestResponse:
        """Test ManifestResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManifestResponse`
        """
        model = ManifestResponse()
        if include_optional:
            return ManifestResponse(
                connector_uri = '',
                staging = '',
                need_sha1 = [
                    ''
                    ],
                deletion_candidates = [
                    mfs_sdk.models.deletion_candidate.DeletionCandidate(
                        path = '', 
                        size = 56, 
                        inode = 56, 
                        sha1 = '', )
                    ]
            )
        else:
            return ManifestResponse(
                connector_uri = '',
                staging = '',
        )
        """

    def testManifestResponse(self):
        """Test ManifestResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
