# coding: utf-8

"""
    MFS

    Multi-source File-like Search — HTTP /v1 control plane.

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mfs_sdk.api.browse_api import BrowseApi


class TestBrowseApi(unittest.TestCase):
    """BrowseApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BrowseApi()

    def tearDown(self) -> None:
        pass

    def test_cat(self) -> None:
        """Test case for cat

        Cat
        """
        pass

    def test_ls(self) -> None:
        """Test case for ls

        Ls
        """
        pass


if __name__ == '__main__':
    unittest.main()
