# coding: utf-8

"""
    MFS

    Multi-source File-like Search — HTTP /v1 control plane.

    The version of the OpenAPI document: 0.4.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mfs_sdk.models.manifest_request import ManifestRequest

class TestManifestRequest(unittest.TestCase):
    """ManifestRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManifestRequest:
        """Test ManifestRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManifestRequest`
        """
        model = ManifestRequest()
        if include_optional:
            return ManifestRequest(
                client_id = '',
                root = '',
                files = [
                    mfs_sdk.models.manifest_file.ManifestFile(
                        path = '', 
                        size = 56, 
                        mtime_ns = 56, 
                        inode = 56, )
                    ]
            )
        else:
            return ManifestRequest(
                client_id = '',
                root = '',
        )
        """

    def testManifestRequest(self):
        """Test ManifestRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
