# coding: utf-8

"""
    MFS

    Multi-source File-like Search — HTTP /v1 control plane.

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mfs_sdk.api.ingest_api import IngestApi


class TestIngestApi(unittest.TestCase):
    """IngestApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IngestApi()

    def tearDown(self) -> None:
        pass

    def test_add_source(self) -> None:
        """Test case for add_source

        Add
        """
        pass

    def test_get_job(self) -> None:
        """Test case for get_job

        Job
        """
        pass


if __name__ == '__main__':
    unittest.main()
