# coding: utf-8

"""
    MFS

    Multi-source File-like Search — HTTP /v1 control plane.

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mfs_sdk.models.connector_row import ConnectorRow

class TestConnectorRow(unittest.TestCase):
    """ConnectorRow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConnectorRow:
        """Test ConnectorRow
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConnectorRow`
        """
        model = ConnectorRow()
        if include_optional:
            return ConnectorRow(
                root_uri = '',
                type = '',
                status = ''
            )
        else:
            return ConnectorRow(
                root_uri = '',
                type = '',
                status = '',
        )
        """

    def testConnectorRow(self):
        """Test ConnectorRow"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
