/* tslint:disable */
/* eslint-disable */
/**
 * MFS
 * Multi-source File-like Search — HTTP /v1 control plane.
 *
 * The version of the OpenAPI document: 0.4.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddRequest
 */
export interface AddRequest {
    /**
     * path or connector URI to register + index
     * @type {string}
     * @memberof AddRequest
     */
    target: string;
    /**
     * connector config ([[objects]], schemas, _credential_ref, ...); the CLI loads this from --config <file.toml>
     * @type {{ [key: string]: any; }}
     * @memberof AddRequest
     */
    config?: { [key: string]: any; } | null;
    /**
     * force full re-index (ignore caches/fingerprints)
     * @type {boolean}
     * @memberof AddRequest
     */
    full?: boolean;
    /**
     * only index changes since this cursor/date
     * @type {string}
     * @memberof AddRequest
     */
    since?: string | null;
    /**
     * False (default): enqueue and return the job_id immediately (poll GET /v1/jobs/{id}); True: index inline and return when done
     * @type {boolean}
     * @memberof AddRequest
     */
    process?: boolean;
    /**
     * apply config to an existing connector (connector update); add ignores it
     * @type {boolean}
     * @memberof AddRequest
     */
    update?: boolean;
}

/**
 * Check if a given object implements the AddRequest interface.
 */
export function instanceOfAddRequest(value: object): value is AddRequest {
    if (!('target' in value) || value['target'] === undefined) return false;
    return true;
}

export function AddRequestFromJSON(json: any): AddRequest {
    return AddRequestFromJSONTyped(json, false);
}

export function AddRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'target': json['target'],
        'config': json['config'] == null ? undefined : json['config'],
        'full': json['full'] == null ? undefined : json['full'],
        'since': json['since'] == null ? undefined : json['since'],
        'process': json['process'] == null ? undefined : json['process'],
        'update': json['update'] == null ? undefined : json['update'],
    };
}

export function AddRequestToJSON(json: any): AddRequest {
    return AddRequestToJSONTyped(json, false);
}

export function AddRequestToJSONTyped(value?: AddRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'target': value['target'],
        'config': value['config'],
        'full': value['full'],
        'since': value['since'],
        'process': value['process'],
        'update': value['update'],
    };
}

