/* tslint:disable */
/* eslint-disable */
/**
 * MFS
 * Multi-source File-like Search — HTTP /v1 control plane.
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GrepMatchModel
 */
export interface GrepMatchModel {
    /**
     * 
     * @type {string}
     * @memberof GrepMatchModel
     */
    source?: string | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof GrepMatchModel
     */
    lines?: Array<number> | null;
    /**
     * 
     * @type {string}
     * @memberof GrepMatchModel
     */
    content?: string;
    /**
     * bm25 | linear | pushdown
     * @type {string}
     * @memberof GrepMatchModel
     */
    via?: string | null;
}

/**
 * Check if a given object implements the GrepMatchModel interface.
 */
export function instanceOfGrepMatchModel(value: object): value is GrepMatchModel {
    return true;
}

export function GrepMatchModelFromJSON(json: any): GrepMatchModel {
    return GrepMatchModelFromJSONTyped(json, false);
}

export function GrepMatchModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): GrepMatchModel {
    if (json == null) {
        return json;
    }
    return {
        
        'source': json['source'] == null ? undefined : json['source'],
        'lines': json['lines'] == null ? undefined : json['lines'],
        'content': json['content'] == null ? undefined : json['content'],
        'via': json['via'] == null ? undefined : json['via'],
    };
}

export function GrepMatchModelToJSON(json: any): GrepMatchModel {
    return GrepMatchModelToJSONTyped(json, false);
}

export function GrepMatchModelToJSONTyped(value?: GrepMatchModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source': value['source'],
        'lines': value['lines'],
        'content': value['content'],
        'via': value['via'],
    };
}

