/* tslint:disable */
/* eslint-disable */
/**
 * MFS
 * Multi-source File-like Search — HTTP /v1 control plane.
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobResponse
 */
export interface JobResponse {
    /**
     * 
     * @type {string}
     * @memberof JobResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof JobResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof JobResponse
     */
    opKind?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobResponse
     */
    trigger?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobResponse
     */
    error?: string | null;
    /**
     * 
     * @type {number}
     * @memberof JobResponse
     */
    totalObjects?: number | null;
    /**
     * 
     * @type {number}
     * @memberof JobResponse
     */
    succeededObjects?: number | null;
    /**
     * 
     * @type {number}
     * @memberof JobResponse
     */
    failedObjects?: number | null;
    /**
     * 
     * @type {number}
     * @memberof JobResponse
     */
    cancelledObjects?: number | null;
    /**
     * 
     * @type {string}
     * @memberof JobResponse
     */
    startedAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobResponse
     */
    finishedAt?: string | null;
}

/**
 * Check if a given object implements the JobResponse interface.
 */
export function instanceOfJobResponse(value: object): value is JobResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function JobResponseFromJSON(json: any): JobResponse {
    return JobResponseFromJSONTyped(json, false);
}

export function JobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'],
        'opKind': json['op_kind'] == null ? undefined : json['op_kind'],
        'trigger': json['trigger'] == null ? undefined : json['trigger'],
        'error': json['error'] == null ? undefined : json['error'],
        'totalObjects': json['total_objects'] == null ? undefined : json['total_objects'],
        'succeededObjects': json['succeeded_objects'] == null ? undefined : json['succeeded_objects'],
        'failedObjects': json['failed_objects'] == null ? undefined : json['failed_objects'],
        'cancelledObjects': json['cancelled_objects'] == null ? undefined : json['cancelled_objects'],
        'startedAt': json['started_at'] == null ? undefined : json['started_at'],
        'finishedAt': json['finished_at'] == null ? undefined : json['finished_at'],
    };
}

export function JobResponseToJSON(json: any): JobResponse {
    return JobResponseToJSONTyped(json, false);
}

export function JobResponseToJSONTyped(value?: JobResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
        'op_kind': value['opKind'],
        'trigger': value['trigger'],
        'error': value['error'],
        'total_objects': value['totalObjects'],
        'succeeded_objects': value['succeededObjects'],
        'failed_objects': value['failedObjects'],
        'cancelled_objects': value['cancelledObjects'],
        'started_at': value['startedAt'],
        'finished_at': value['finishedAt'],
    };
}

