/* tslint:disable */
/* eslint-disable */
/**
 * MFS
 * Multi-source File-like Search — HTTP /v1 control plane.
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LsEntry
 */
export interface LsEntry {
    /**
     * 
     * @type {string}
     * @memberof LsEntry
     */
    name: string;
    /**
     * file | dir
     * @type {string}
     * @memberof LsEntry
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof LsEntry
     */
    mediaType?: string | null;
    /**
     * 
     * @type {number}
     * @memberof LsEntry
     */
    sizeHint?: number | null;
}

/**
 * Check if a given object implements the LsEntry interface.
 */
export function instanceOfLsEntry(value: object): value is LsEntry {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function LsEntryFromJSON(json: any): LsEntry {
    return LsEntryFromJSONTyped(json, false);
}

export function LsEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): LsEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'mediaType': json['media_type'] == null ? undefined : json['media_type'],
        'sizeHint': json['size_hint'] == null ? undefined : json['size_hint'],
    };
}

export function LsEntryToJSON(json: any): LsEntry {
    return LsEntryToJSONTyped(json, false);
}

export function LsEntryToJSONTyped(value?: LsEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'media_type': value['mediaType'],
        'size_hint': value['sizeHint'],
    };
}

