/* tslint:disable */
/* eslint-disable */
/**
 * MFS
 * Multi-source File-like Search — HTTP /v1 control plane.
 *
 * The version of the OpenAPI document: 0.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ManifestFile
 */
export interface ManifestFile {
    /**
     * path relative to the upload root
     * @type {string}
     * @memberof ManifestFile
     */
    path: string;
    /**
     * 
     * @type {number}
     * @memberof ManifestFile
     */
    size: number;
    /**
     * 
     * @type {number}
     * @memberof ManifestFile
     */
    mtimeNs: number;
    /**
     * 
     * @type {number}
     * @memberof ManifestFile
     */
    inode?: number | null;
}

/**
 * Check if a given object implements the ManifestFile interface.
 */
export function instanceOfManifestFile(value: object): value is ManifestFile {
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    if (!('mtimeNs' in value) || value['mtimeNs'] === undefined) return false;
    return true;
}

export function ManifestFileFromJSON(json: any): ManifestFile {
    return ManifestFileFromJSONTyped(json, false);
}

export function ManifestFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManifestFile {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'],
        'size': json['size'],
        'mtimeNs': json['mtime_ns'],
        'inode': json['inode'] == null ? undefined : json['inode'],
    };
}

export function ManifestFileToJSON(json: any): ManifestFile {
    return ManifestFileToJSONTyped(json, false);
}

export function ManifestFileToJSONTyped(value?: ManifestFile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'size': value['size'],
        'mtime_ns': value['mtimeNs'],
        'inode': value['inode'],
    };
}

