/* tslint:disable */
/* eslint-disable */
/**
 * MFS
 * Multi-source File-like Search — HTTP /v1 control plane.
 *
 * The version of the OpenAPI document: 0.4.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProbeResponse
 */
export interface ProbeResponse {
    /**
     * 
     * @type {string}
     * @memberof ProbeResponse
     */
    target: string;
    /**
     * 
     * @type {string}
     * @memberof ProbeResponse
     */
    type: string;
    /**
     * 
     * @type {boolean}
     * @memberof ProbeResponse
     */
    ok: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProbeResponse
     */
    detail?: string;
}

/**
 * Check if a given object implements the ProbeResponse interface.
 */
export function instanceOfProbeResponse(value: object): value is ProbeResponse {
    if (!('target' in value) || value['target'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function ProbeResponseFromJSON(json: any): ProbeResponse {
    return ProbeResponseFromJSONTyped(json, false);
}

export function ProbeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProbeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'target': json['target'],
        'type': json['type'],
        'ok': json['ok'],
        'detail': json['detail'] == null ? undefined : json['detail'],
    };
}

export function ProbeResponseToJSON(json: any): ProbeResponse {
    return ProbeResponseToJSONTyped(json, false);
}

export function ProbeResponseToJSONTyped(value?: ProbeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'target': value['target'],
        'type': value['type'],
        'ok': value['ok'],
        'detail': value['detail'],
    };
}

