/* tslint:disable */
/* eslint-disable */
/**
 * MFS
 * Multi-source File-like Search — HTTP /v1 control plane.
 *
 * The version of the OpenAPI document: 0.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProbeRequest
 */
export interface ProbeRequest {
    /**
     * 
     * @type {string}
     * @memberof ProbeRequest
     */
    target: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ProbeRequest
     */
    config?: { [key: string]: any; } | null;
}

/**
 * Check if a given object implements the ProbeRequest interface.
 */
export function instanceOfProbeRequest(value: object): value is ProbeRequest {
    if (!('target' in value) || value['target'] === undefined) return false;
    return true;
}

export function ProbeRequestFromJSON(json: any): ProbeRequest {
    return ProbeRequestFromJSONTyped(json, false);
}

export function ProbeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProbeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'target': json['target'],
        'config': json['config'] == null ? undefined : json['config'],
    };
}

export function ProbeRequestToJSON(json: any): ProbeRequest {
    return ProbeRequestToJSONTyped(json, false);
}

export function ProbeRequestToJSONTyped(value?: ProbeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'target': value['target'],
        'config': value['config'],
    };
}

