/* tslint:disable */
/* eslint-disable */
/**
 * MFS
 * Multi-source File-like Search — HTTP /v1 control plane.
 *
 * The version of the OpenAPI document: 0.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RemoveResponse
 */
export interface RemoveResponse {
    /**
     * 
     * @type {string}
     * @memberof RemoveResponse
     */
    target: string;
    /**
     * 
     * @type {boolean}
     * @memberof RemoveResponse
     */
    removed: boolean;
}

/**
 * Check if a given object implements the RemoveResponse interface.
 */
export function instanceOfRemoveResponse(value: object): value is RemoveResponse {
    if (!('target' in value) || value['target'] === undefined) return false;
    if (!('removed' in value) || value['removed'] === undefined) return false;
    return true;
}

export function RemoveResponseFromJSON(json: any): RemoveResponse {
    return RemoveResponseFromJSONTyped(json, false);
}

export function RemoveResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoveResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'target': json['target'],
        'removed': json['removed'],
    };
}

export function RemoveResponseToJSON(json: any): RemoveResponse {
    return RemoveResponseToJSONTyped(json, false);
}

export function RemoveResponseToJSONTyped(value?: RemoveResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'target': value['target'],
        'removed': value['removed'],
    };
}

