# coding: utf-8

"""
    MFS

    Multi-source File-like Search — HTTP /v1 control plane.

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GrepMatchModel(BaseModel):
    """
    GrepMatchModel
    """ # noqa: E501
    source: Optional[StrictStr] = None
    locator: Optional[Dict[str, Any]] = Field(default=None, description="per-hit identity. text/code line hits: {'lines':[n,n]}; structured pushdown: connector PK dict; notice rows: null.")
    content: Optional[StrictStr] = ''
    via: Optional[StrictStr] = Field(default=None, description="bm25 | linear | pushdown | notice")
    __properties: ClassVar[List[str]] = ["source", "locator", "content", "via"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GrepMatchModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if source (nullable) is None
        # and model_fields_set contains the field
        if self.source is None and "source" in self.model_fields_set:
            _dict['source'] = None

        # set to None if locator (nullable) is None
        # and model_fields_set contains the field
        if self.locator is None and "locator" in self.model_fields_set:
            _dict['locator'] = None

        # set to None if via (nullable) is None
        # and model_fields_set contains the field
        if self.via is None and "via" in self.model_fields_set:
            _dict['via'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GrepMatchModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "source": obj.get("source"),
            "locator": obj.get("locator"),
            "content": obj.get("content") if obj.get("content") is not None else '',
            "via": obj.get("via")
        })
        return _obj


