# coding: utf-8

"""
    MFS

    Multi-source File-like Search — HTTP /v1 control plane.

    The version of the OpenAPI document: 0.4.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class LsEntry(BaseModel):
    """
    LsEntry
    """ # noqa: E501
    name: StrictStr
    type: StrictStr = Field(description="file | dir")
    media_type: Optional[StrictStr] = None
    size_hint: Optional[StrictInt] = None
    path: Optional[StrictStr] = Field(default=None, description="full object URI — feed to cat/search")
    search_status: Optional[StrictStr] = Field(default=None, description="indexed | partial | not_indexed | null if unseen")
    indexable: Optional[StrictBool] = Field(default=None, description="whether this object is eligible for indexing")
    __properties: ClassVar[List[str]] = ["name", "type", "media_type", "size_hint", "path", "search_status", "indexable"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LsEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if media_type (nullable) is None
        # and model_fields_set contains the field
        if self.media_type is None and "media_type" in self.model_fields_set:
            _dict['media_type'] = None

        # set to None if size_hint (nullable) is None
        # and model_fields_set contains the field
        if self.size_hint is None and "size_hint" in self.model_fields_set:
            _dict['size_hint'] = None

        # set to None if path (nullable) is None
        # and model_fields_set contains the field
        if self.path is None and "path" in self.model_fields_set:
            _dict['path'] = None

        # set to None if search_status (nullable) is None
        # and model_fields_set contains the field
        if self.search_status is None and "search_status" in self.model_fields_set:
            _dict['search_status'] = None

        # set to None if indexable (nullable) is None
        # and model_fields_set contains the field
        if self.indexable is None and "indexable" in self.model_fields_set:
            _dict['indexable'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LsEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "type": obj.get("type"),
            "media_type": obj.get("media_type"),
            "size_hint": obj.get("size_hint"),
            "path": obj.get("path"),
            "search_status": obj.get("search_status"),
            "indexable": obj.get("indexable")
        })
        return _obj


