# coding: utf-8

"""
    MFS

    Multi-source File-like Search — HTTP /v1 control plane.

    The version of the OpenAPI document: 0.4.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from mfs_sdk.models.deletion_candidate import DeletionCandidate
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ManifestResponse(BaseModel):
    """
    ManifestResponse
    """ # noqa: E501
    connector_uri: StrictStr
    staging: StrictStr
    need_sha1: Optional[List[StrictStr]] = Field(default=None, description="paths whose bytes the server needs")
    deletion_candidates: Optional[List[DeletionCandidate]] = Field(default=None, description="server-known paths absent from the manifest (for rename pairing)")
    __properties: ClassVar[List[str]] = ["connector_uri", "staging", "need_sha1", "deletion_candidates"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ManifestResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in deletion_candidates (list)
        _items = []
        if self.deletion_candidates:
            for _item_deletion_candidates in self.deletion_candidates:
                if _item_deletion_candidates:
                    _items.append(_item_deletion_candidates.to_dict())
            _dict['deletion_candidates'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ManifestResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "connector_uri": obj.get("connector_uri"),
            "staging": obj.get("staging"),
            "need_sha1": obj.get("need_sha1"),
            "deletion_candidates": [DeletionCandidate.from_dict(_item) for _item in obj["deletion_candidates"]] if obj.get("deletion_candidates") is not None else None
        })
        return _obj


