/* tslint:disable */
/* eslint-disable */
/**
 * MFS
 * Multi-source File-like Search — HTTP /v1 control plane.
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CatResponse,
    CatResponseFromJSON,
    CatResponseToJSON,
} from '../models/CatResponse';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type LsResponse,
    LsResponseFromJSON,
    LsResponseToJSON,
} from '../models/LsResponse';

export interface CatRequest {
    path: string;
    range?: string | null;
    meta?: boolean;
    density?: string | null;
}

export interface LsRequest {
    path: string;
}

/**
 * 
 */
export class BrowseApi extends runtime.BaseAPI {

    /**
     * Creates request options for cat without sending the request
     */
    async catRequestOpts(requestParameters: CatRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['path'] == null) {
            throw new runtime.RequiredError(
                'path',
                'Required parameter "path" was null or undefined when calling cat().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['path'] != null) {
            queryParameters['path'] = requestParameters['path'];
        }

        if (requestParameters['range'] != null) {
            queryParameters['range'] = requestParameters['range'];
        }

        if (requestParameters['meta'] != null) {
            queryParameters['meta'] = requestParameters['meta'];
        }

        if (requestParameters['density'] != null) {
            queryParameters['density'] = requestParameters['density'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/cat`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Cat
     */
    async catRaw(requestParameters: CatRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CatResponse>> {
        const requestOptions = await this.catRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CatResponseFromJSON(jsonValue));
    }

    /**
     * Cat
     */
    async cat(requestParameters: CatRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CatResponse> {
        const response = await this.catRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ls without sending the request
     */
    async lsRequestOpts(requestParameters: LsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['path'] == null) {
            throw new runtime.RequiredError(
                'path',
                'Required parameter "path" was null or undefined when calling ls().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['path'] != null) {
            queryParameters['path'] = requestParameters['path'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/ls`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Ls
     */
    async lsRaw(requestParameters: LsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LsResponse>> {
        const requestOptions = await this.lsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LsResponseFromJSON(jsonValue));
    }

    /**
     * Ls
     */
    async ls(requestParameters: LsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LsResponse> {
        const response = await this.lsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
