/* tslint:disable */
/* eslint-disable */
/**
 * MFS
 * Multi-source File-like Search — HTTP /v1 control plane.
 *
 * The version of the OpenAPI document: 0.4.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CatResponse,
    CatResponseFromJSON,
    CatResponseToJSON,
} from '../models/CatResponse';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type LsResponse,
    LsResponseFromJSON,
    LsResponseToJSON,
} from '../models/LsResponse';

export interface ExportRequest {
    path: string;
}

export interface CatRequest {
    path: string;
    range?: string | null;
    meta?: boolean;
    density?: string | null;
    locator?: string | null;
}

export interface HeadRequest {
    path: string;
    n?: number;
}

export interface LsRequest {
    path: string;
}

export interface TailRequest {
    path: string;
    n?: number;
}

/**
 * 
 */
export class BrowseApi extends runtime.BaseAPI {

    /**
     * Creates request options for _export without sending the request
     */
    async _exportRequestOpts(requestParameters: ExportRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['path'] == null) {
            throw new runtime.RequiredError(
                'path',
                'Required parameter "path" was null or undefined when calling _export().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['path'] != null) {
            queryParameters['path'] = requestParameters['path'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/export`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Full object content for `mfs export`. Honest about completeness: each connector\'s own row cap still applies (postgres `max_read_rows`, BigQuery `max_read_rows`, etc.), so structured objects above that threshold return `partial=true`. The bare-cat size guard (object_too_large_for_cat) does NOT apply — export is the escape hatch for that — but true streaming export is still TODO.
     * Export
     */
    async _exportRaw(requestParameters: ExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CatResponse>> {
        const requestOptions = await this._exportRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CatResponseFromJSON(jsonValue));
    }

    /**
     * Full object content for `mfs export`. Honest about completeness: each connector\'s own row cap still applies (postgres `max_read_rows`, BigQuery `max_read_rows`, etc.), so structured objects above that threshold return `partial=true`. The bare-cat size guard (object_too_large_for_cat) does NOT apply — export is the escape hatch for that — but true streaming export is still TODO.
     * Export
     */
    async _export(requestParameters: ExportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CatResponse> {
        const response = await this._exportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for cat without sending the request
     */
    async catRequestOpts(requestParameters: CatRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['path'] == null) {
            throw new runtime.RequiredError(
                'path',
                'Required parameter "path" was null or undefined when calling cat().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['path'] != null) {
            queryParameters['path'] = requestParameters['path'];
        }

        if (requestParameters['range'] != null) {
            queryParameters['range'] = requestParameters['range'];
        }

        if (requestParameters['meta'] != null) {
            queryParameters['meta'] = requestParameters['meta'];
        }

        if (requestParameters['density'] != null) {
            queryParameters['density'] = requestParameters['density'];
        }

        if (requestParameters['locator'] != null) {
            queryParameters['locator'] = requestParameters['locator'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/cat`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Cat
     */
    async catRaw(requestParameters: CatRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CatResponse>> {
        const requestOptions = await this.catRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CatResponseFromJSON(jsonValue));
    }

    /**
     * Cat
     */
    async cat(requestParameters: CatRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CatResponse> {
        const response = await this.catRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for head without sending the request
     */
    async headRequestOpts(requestParameters: HeadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['path'] == null) {
            throw new runtime.RequiredError(
                'path',
                'Required parameter "path" was null or undefined when calling head().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['path'] != null) {
            queryParameters['path'] = requestParameters['path'];
        }

        if (requestParameters['n'] != null) {
            queryParameters['n'] = requestParameters['n'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/head`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Head
     */
    async headRaw(requestParameters: HeadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CatResponse>> {
        const requestOptions = await this.headRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CatResponseFromJSON(jsonValue));
    }

    /**
     * Head
     */
    async head(requestParameters: HeadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CatResponse> {
        const response = await this.headRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ls without sending the request
     */
    async lsRequestOpts(requestParameters: LsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['path'] == null) {
            throw new runtime.RequiredError(
                'path',
                'Required parameter "path" was null or undefined when calling ls().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['path'] != null) {
            queryParameters['path'] = requestParameters['path'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/ls`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Ls
     */
    async lsRaw(requestParameters: LsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LsResponse>> {
        const requestOptions = await this.lsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LsResponseFromJSON(jsonValue));
    }

    /**
     * Ls
     */
    async ls(requestParameters: LsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LsResponse> {
        const response = await this.lsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for tail without sending the request
     */
    async tailRequestOpts(requestParameters: TailRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['path'] == null) {
            throw new runtime.RequiredError(
                'path',
                'Required parameter "path" was null or undefined when calling tail().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['path'] != null) {
            queryParameters['path'] = requestParameters['path'];
        }

        if (requestParameters['n'] != null) {
            queryParameters['n'] = requestParameters['n'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/tail`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Tail
     */
    async tailRaw(requestParameters: TailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CatResponse>> {
        const requestOptions = await this.tailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CatResponseFromJSON(jsonValue));
    }

    /**
     * Tail
     */
    async tail(requestParameters: TailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CatResponse> {
        const response = await this.tailRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
