/* tslint:disable */
/* eslint-disable */
/**
 * MFS
 * Multi-source File-like Search — HTTP /v1 control plane.
 *
 * The version of the OpenAPI document: 0.4.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type EstimateResponse,
    EstimateResponseFromJSON,
    EstimateResponseToJSON,
} from '../models/EstimateResponse';
import {
    type ProbeRequest,
    ProbeRequestFromJSON,
    ProbeRequestToJSON,
} from '../models/ProbeRequest';
import {
    type ProbeResponse,
    ProbeResponseFromJSON,
    ProbeResponseToJSON,
} from '../models/ProbeResponse';
import {
    type RemoveResponse,
    RemoveResponseFromJSON,
    RemoveResponseToJSON,
} from '../models/RemoveResponse';

export interface EstimateConnectorRequest {
    probeRequest: ProbeRequest;
}

export interface InspectConnectorRequest {
    target: string;
}

export interface ProbeConnectorRequest {
    probeRequest: ProbeRequest;
}

export interface RemoveConnectorRequest {
    target: string;
}

/**
 * 
 */
export class ConnectorsApi extends runtime.BaseAPI {

    /**
     * Creates request options for estimateConnector without sending the request
     */
    async estimateConnectorRequestOpts(requestParameters: EstimateConnectorRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['probeRequest'] == null) {
            throw new runtime.RequiredError(
                'probeRequest',
                'Required parameter "probeRequest" was null or undefined when calling estimateConnector().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connectors/estimate`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProbeRequestToJSON(requestParameters['probeRequest']),
        };
    }

    /**
     * Zero-billing pre-flight estimate: object/chunk/token counts via metadata + a local chunker/tokenizer dry-run. No embedding API calls.
     * Estimate
     */
    async estimateConnectorRaw(requestParameters: EstimateConnectorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EstimateResponse>> {
        const requestOptions = await this.estimateConnectorRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EstimateResponseFromJSON(jsonValue));
    }

    /**
     * Zero-billing pre-flight estimate: object/chunk/token counts via metadata + a local chunker/tokenizer dry-run. No embedding API calls.
     * Estimate
     */
    async estimateConnector(requestParameters: EstimateConnectorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EstimateResponse> {
        const response = await this.estimateConnectorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for inspectConnector without sending the request
     */
    async inspectConnectorRequestOpts(requestParameters: InspectConnectorRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['target'] == null) {
            throw new runtime.RequiredError(
                'target',
                'Required parameter "target" was null or undefined when calling inspectConnector().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['target'] != null) {
            queryParameters['target'] = requestParameters['target'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connectors/inspect`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Inspect
     */
    async inspectConnectorRaw(requestParameters: InspectConnectorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.inspectConnectorRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Inspect
     */
    async inspectConnector(requestParameters: InspectConnectorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.inspectConnectorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for probeConnector without sending the request
     */
    async probeConnectorRequestOpts(requestParameters: ProbeConnectorRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['probeRequest'] == null) {
            throw new runtime.RequiredError(
                'probeRequest',
                'Required parameter "probeRequest" was null or undefined when calling probeConnector().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connectors/probe`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProbeRequestToJSON(requestParameters['probeRequest']),
        };
    }

    /**
     * Probe
     */
    async probeConnectorRaw(requestParameters: ProbeConnectorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProbeResponse>> {
        const requestOptions = await this.probeConnectorRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProbeResponseFromJSON(jsonValue));
    }

    /**
     * Probe
     */
    async probeConnector(requestParameters: ProbeConnectorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProbeResponse> {
        const response = await this.probeConnectorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for removeConnector without sending the request
     */
    async removeConnectorRequestOpts(requestParameters: RemoveConnectorRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['target'] == null) {
            throw new runtime.RequiredError(
                'target',
                'Required parameter "target" was null or undefined when calling removeConnector().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['target'] != null) {
            queryParameters['target'] = requestParameters['target'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/connectors`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove
     */
    async removeConnectorRaw(requestParameters: RemoveConnectorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RemoveResponse>> {
        const requestOptions = await this.removeConnectorRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RemoveResponseFromJSON(jsonValue));
    }

    /**
     * Remove
     */
    async removeConnector(requestParameters: RemoveConnectorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RemoveResponse> {
        const response = await this.removeConnectorRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
