/* tslint:disable */
/* eslint-disable */
/**
 * MFS
 * Multi-source File-like Search — HTTP /v1 control plane.
 *
 * The version of the OpenAPI document: 0.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ErrorResponse,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/ErrorResponse';
import {
    type GrepResponse,
    GrepResponseFromJSON,
    GrepResponseToJSON,
} from '../models/GrepResponse';
import {
    type SearchResponse,
    SearchResponseFromJSON,
    SearchResponseToJSON,
} from '../models/SearchResponse';

export interface GrepRequest {
    pattern: string;
    path: string;
}

export interface SearchRequest {
    q: string;
    path?: string | null;
    mode?: SearchModeEnum;
    topK?: number;
    collapse?: boolean;
    kind?: string | null;
}

/**
 * 
 */
export class RetrievalApi extends runtime.BaseAPI {

    /**
     * Creates request options for grep without sending the request
     */
    async grepRequestOpts(requestParameters: GrepRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pattern'] == null) {
            throw new runtime.RequiredError(
                'pattern',
                'Required parameter "pattern" was null or undefined when calling grep().'
            );
        }

        if (requestParameters['path'] == null) {
            throw new runtime.RequiredError(
                'path',
                'Required parameter "path" was null or undefined when calling grep().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pattern'] != null) {
            queryParameters['pattern'] = requestParameters['pattern'];
        }

        if (requestParameters['path'] != null) {
            queryParameters['path'] = requestParameters['path'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/grep`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Grep
     */
    async grepRaw(requestParameters: GrepRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GrepResponse>> {
        const requestOptions = await this.grepRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GrepResponseFromJSON(jsonValue));
    }

    /**
     * Grep
     */
    async grep(requestParameters: GrepRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GrepResponse> {
        const response = await this.grepRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for search without sending the request
     */
    async searchRequestOpts(requestParameters: SearchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['q'] == null) {
            throw new runtime.RequiredError(
                'q',
                'Required parameter "q" was null or undefined when calling search().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['path'] != null) {
            queryParameters['path'] = requestParameters['path'];
        }

        if (requestParameters['mode'] != null) {
            queryParameters['mode'] = requestParameters['mode'];
        }

        if (requestParameters['topK'] != null) {
            queryParameters['top_k'] = requestParameters['topK'];
        }

        if (requestParameters['collapse'] != null) {
            queryParameters['collapse'] = requestParameters['collapse'];
        }

        if (requestParameters['kind'] != null) {
            queryParameters['kind'] = requestParameters['kind'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/search`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Search
     */
    async searchRaw(requestParameters: SearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchResponse>> {
        const requestOptions = await this.searchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchResponseFromJSON(jsonValue));
    }

    /**
     * Search
     */
    async search(requestParameters: SearchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchResponse> {
        const response = await this.searchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const SearchModeEnum = {
    Hybrid: 'hybrid',
    Semantic: 'semantic',
    Keyword: 'keyword'
} as const;
export type SearchModeEnum = typeof SearchModeEnum[keyof typeof SearchModeEnum];
