/*
 * MFS
 * Multi-source File-like Search — HTTP /v1 control plane.
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.zilliz.mfs.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.zilliz.mfs.model.ConnectorRow;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.zilliz.mfs.JSON;

/**
 * StatusResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-26T04:25:09.503817Z[Etc/UTC]", comments = "Generator version: 7.22.0")
public class StatusResponse {
  public static final String SERIALIZED_NAME_CONNECTORS = "connectors";
  @SerializedName(SERIALIZED_NAME_CONNECTORS)
  @javax.annotation.Nonnull
  private List<ConnectorRow> connectors = new ArrayList<>();

  public static final String SERIALIZED_NAME_JOBS = "jobs";
  @SerializedName(SERIALIZED_NAME_JOBS)
  @javax.annotation.Nullable
  private Map<String, Integer> jobs = new HashMap<>();

  public StatusResponse() {
  }

  public StatusResponse connectors(@javax.annotation.Nonnull List<ConnectorRow> connectors) {
    this.connectors = connectors;
    return this;
  }

  public StatusResponse addConnectorsItem(ConnectorRow connectorsItem) {
    if (this.connectors == null) {
      this.connectors = new ArrayList<>();
    }
    this.connectors.add(connectorsItem);
    return this;
  }

  /**
   * Get connectors
   * @return connectors
   */
  @javax.annotation.Nonnull
  public List<ConnectorRow> getConnectors() {
    return connectors;
  }

  public void setConnectors(@javax.annotation.Nonnull List<ConnectorRow> connectors) {
    this.connectors = connectors;
  }


  public StatusResponse jobs(@javax.annotation.Nullable Map<String, Integer> jobs) {
    this.jobs = jobs;
    return this;
  }

  public StatusResponse putJobsItem(String key, Integer jobsItem) {
    if (this.jobs == null) {
      this.jobs = new HashMap<>();
    }
    this.jobs.put(key, jobsItem);
    return this;
  }

  /**
   * count of jobs by status
   * @return jobs
   */
  @javax.annotation.Nullable
  public Map<String, Integer> getJobs() {
    return jobs;
  }

  public void setJobs(@javax.annotation.Nullable Map<String, Integer> jobs) {
    this.jobs = jobs;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatusResponse statusResponse = (StatusResponse) o;
    return Objects.equals(this.connectors, statusResponse.connectors) &&
        Objects.equals(this.jobs, statusResponse.jobs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(connectors, jobs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatusResponse {\n");
    sb.append("    connectors: ").append(toIndentedString(connectors)).append("\n");
    sb.append("    jobs: ").append(toIndentedString(jobs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("connectors", "jobs"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("connectors"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to StatusResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!StatusResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in StatusResponse is not found in the empty JSON string", StatusResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!StatusResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `StatusResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : StatusResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("connectors") != null) {
        if (!jsonObj.get("connectors").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `connectors` to be an array in the JSON string but got `%s`", jsonObj.get("connectors").toString()));
        }
        JsonArray jsonArrayconnectors = jsonObj.getAsJsonArray("connectors");
        // validate the required field `connectors` (array)
        for (int i = 0; i < jsonArrayconnectors.size(); i++) {
          ConnectorRow.validateJsonElement(jsonArrayconnectors.get(i));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!StatusResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'StatusResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<StatusResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(StatusResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<StatusResponse>() {
           @Override
           public void write(JsonWriter out, StatusResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public StatusResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of StatusResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of StatusResponse
   * @throws IOException if the JSON string is invalid with respect to StatusResponse
   */
  public static StatusResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, StatusResponse.class);
  }

  /**
   * Convert an instance of StatusResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

