/*
MFS

Multi-source File-like Search — HTTP /v1 control plane.

API version: 0.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mfssdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CancelResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CancelResponse{}

// CancelResponse struct for CancelResponse
type CancelResponse struct {
	JobId string `json:"job_id"`
	Cancelled bool `json:"cancelled"`
}

type _CancelResponse CancelResponse

// NewCancelResponse instantiates a new CancelResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCancelResponse(jobId string, cancelled bool) *CancelResponse {
	this := CancelResponse{}
	this.JobId = jobId
	this.Cancelled = cancelled
	return &this
}

// NewCancelResponseWithDefaults instantiates a new CancelResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCancelResponseWithDefaults() *CancelResponse {
	this := CancelResponse{}
	return &this
}

// GetJobId returns the JobId field value
func (o *CancelResponse) GetJobId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value
// and a boolean to check if the value has been set.
func (o *CancelResponse) GetJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobId, true
}

// SetJobId sets field value
func (o *CancelResponse) SetJobId(v string) {
	o.JobId = v
}

// GetCancelled returns the Cancelled field value
func (o *CancelResponse) GetCancelled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Cancelled
}

// GetCancelledOk returns a tuple with the Cancelled field value
// and a boolean to check if the value has been set.
func (o *CancelResponse) GetCancelledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cancelled, true
}

// SetCancelled sets field value
func (o *CancelResponse) SetCancelled(v bool) {
	o.Cancelled = v
}

func (o CancelResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CancelResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["job_id"] = o.JobId
	toSerialize["cancelled"] = o.Cancelled
	return toSerialize, nil
}

func (o *CancelResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"job_id",
		"cancelled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCancelResponse := _CancelResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCancelResponse)

	if err != nil {
		return err
	}

	*o = CancelResponse(varCancelResponse)

	return err
}

type NullableCancelResponse struct {
	value *CancelResponse
	isSet bool
}

func (v NullableCancelResponse) Get() *CancelResponse {
	return v.value
}

func (v *NullableCancelResponse) Set(val *CancelResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCancelResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCancelResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCancelResponse(val *CancelResponse) *NullableCancelResponse {
	return &NullableCancelResponse{value: val, isSet: true}
}

func (v NullableCancelResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCancelResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


