/*
MFS

Multi-source File-like Search — HTTP /v1 control plane.

API version: 0.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mfssdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CatResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CatResponse{}

// CatResponse struct for CatResponse
type CatResponse struct {
	Source string `json:"source"`
	Content string `json:"content"`
}

type _CatResponse CatResponse

// NewCatResponse instantiates a new CatResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatResponse(source string, content string) *CatResponse {
	this := CatResponse{}
	this.Source = source
	this.Content = content
	return &this
}

// NewCatResponseWithDefaults instantiates a new CatResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatResponseWithDefaults() *CatResponse {
	this := CatResponse{}
	return &this
}

// GetSource returns the Source field value
func (o *CatResponse) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *CatResponse) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *CatResponse) SetSource(v string) {
	o.Source = v
}

// GetContent returns the Content field value
func (o *CatResponse) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *CatResponse) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *CatResponse) SetContent(v string) {
	o.Content = v
}

func (o CatResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CatResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["source"] = o.Source
	toSerialize["content"] = o.Content
	return toSerialize, nil
}

func (o *CatResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"source",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCatResponse := _CatResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCatResponse)

	if err != nil {
		return err
	}

	*o = CatResponse(varCatResponse)

	return err
}

type NullableCatResponse struct {
	value *CatResponse
	isSet bool
}

func (v NullableCatResponse) Get() *CatResponse {
	return v.value
}

func (v *NullableCatResponse) Set(val *CatResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCatResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCatResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatResponse(val *CatResponse) *NullableCatResponse {
	return &NullableCatResponse{value: val, isSet: true}
}

func (v NullableCatResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


