/*
MFS

Multi-source File-like Search — HTTP /v1 control plane.

API version: 0.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mfssdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JobResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobResponse{}

// JobResponse struct for JobResponse
type JobResponse struct {
	Id string `json:"id"`
	Status string `json:"status"`
	OpKind NullableString `json:"op_kind,omitempty"`
	Trigger NullableString `json:"trigger,omitempty"`
	Error NullableString `json:"error,omitempty"`
	TotalObjects NullableInt32 `json:"total_objects,omitempty"`
	SucceededObjects NullableInt32 `json:"succeeded_objects,omitempty"`
	FailedObjects NullableInt32 `json:"failed_objects,omitempty"`
	CancelledObjects NullableInt32 `json:"cancelled_objects,omitempty"`
	StartedAt NullableString `json:"started_at,omitempty"`
	FinishedAt NullableString `json:"finished_at,omitempty"`
}

type _JobResponse JobResponse

// NewJobResponse instantiates a new JobResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobResponse(id string, status string) *JobResponse {
	this := JobResponse{}
	this.Id = id
	this.Status = status
	return &this
}

// NewJobResponseWithDefaults instantiates a new JobResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobResponseWithDefaults() *JobResponse {
	this := JobResponse{}
	return &this
}

// GetId returns the Id field value
func (o *JobResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *JobResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *JobResponse) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *JobResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *JobResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *JobResponse) SetStatus(v string) {
	o.Status = v
}

// GetOpKind returns the OpKind field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobResponse) GetOpKind() string {
	if o == nil || IsNil(o.OpKind.Get()) {
		var ret string
		return ret
	}
	return *o.OpKind.Get()
}

// GetOpKindOk returns a tuple with the OpKind field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobResponse) GetOpKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OpKind.Get(), o.OpKind.IsSet()
}

// HasOpKind returns a boolean if a field has been set.
func (o *JobResponse) HasOpKind() bool {
	if o != nil && o.OpKind.IsSet() {
		return true
	}

	return false
}

// SetOpKind gets a reference to the given NullableString and assigns it to the OpKind field.
func (o *JobResponse) SetOpKind(v string) {
	o.OpKind.Set(&v)
}
// SetOpKindNil sets the value for OpKind to be an explicit nil
func (o *JobResponse) SetOpKindNil() {
	o.OpKind.Set(nil)
}

// UnsetOpKind ensures that no value is present for OpKind, not even an explicit nil
func (o *JobResponse) UnsetOpKind() {
	o.OpKind.Unset()
}

// GetTrigger returns the Trigger field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobResponse) GetTrigger() string {
	if o == nil || IsNil(o.Trigger.Get()) {
		var ret string
		return ret
	}
	return *o.Trigger.Get()
}

// GetTriggerOk returns a tuple with the Trigger field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobResponse) GetTriggerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Trigger.Get(), o.Trigger.IsSet()
}

// HasTrigger returns a boolean if a field has been set.
func (o *JobResponse) HasTrigger() bool {
	if o != nil && o.Trigger.IsSet() {
		return true
	}

	return false
}

// SetTrigger gets a reference to the given NullableString and assigns it to the Trigger field.
func (o *JobResponse) SetTrigger(v string) {
	o.Trigger.Set(&v)
}
// SetTriggerNil sets the value for Trigger to be an explicit nil
func (o *JobResponse) SetTriggerNil() {
	o.Trigger.Set(nil)
}

// UnsetTrigger ensures that no value is present for Trigger, not even an explicit nil
func (o *JobResponse) UnsetTrigger() {
	o.Trigger.Unset()
}

// GetError returns the Error field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobResponse) GetError() string {
	if o == nil || IsNil(o.Error.Get()) {
		var ret string
		return ret
	}
	return *o.Error.Get()
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobResponse) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Error.Get(), o.Error.IsSet()
}

// HasError returns a boolean if a field has been set.
func (o *JobResponse) HasError() bool {
	if o != nil && o.Error.IsSet() {
		return true
	}

	return false
}

// SetError gets a reference to the given NullableString and assigns it to the Error field.
func (o *JobResponse) SetError(v string) {
	o.Error.Set(&v)
}
// SetErrorNil sets the value for Error to be an explicit nil
func (o *JobResponse) SetErrorNil() {
	o.Error.Set(nil)
}

// UnsetError ensures that no value is present for Error, not even an explicit nil
func (o *JobResponse) UnsetError() {
	o.Error.Unset()
}

// GetTotalObjects returns the TotalObjects field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobResponse) GetTotalObjects() int32 {
	if o == nil || IsNil(o.TotalObjects.Get()) {
		var ret int32
		return ret
	}
	return *o.TotalObjects.Get()
}

// GetTotalObjectsOk returns a tuple with the TotalObjects field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobResponse) GetTotalObjectsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TotalObjects.Get(), o.TotalObjects.IsSet()
}

// HasTotalObjects returns a boolean if a field has been set.
func (o *JobResponse) HasTotalObjects() bool {
	if o != nil && o.TotalObjects.IsSet() {
		return true
	}

	return false
}

// SetTotalObjects gets a reference to the given NullableInt32 and assigns it to the TotalObjects field.
func (o *JobResponse) SetTotalObjects(v int32) {
	o.TotalObjects.Set(&v)
}
// SetTotalObjectsNil sets the value for TotalObjects to be an explicit nil
func (o *JobResponse) SetTotalObjectsNil() {
	o.TotalObjects.Set(nil)
}

// UnsetTotalObjects ensures that no value is present for TotalObjects, not even an explicit nil
func (o *JobResponse) UnsetTotalObjects() {
	o.TotalObjects.Unset()
}

// GetSucceededObjects returns the SucceededObjects field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobResponse) GetSucceededObjects() int32 {
	if o == nil || IsNil(o.SucceededObjects.Get()) {
		var ret int32
		return ret
	}
	return *o.SucceededObjects.Get()
}

// GetSucceededObjectsOk returns a tuple with the SucceededObjects field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobResponse) GetSucceededObjectsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SucceededObjects.Get(), o.SucceededObjects.IsSet()
}

// HasSucceededObjects returns a boolean if a field has been set.
func (o *JobResponse) HasSucceededObjects() bool {
	if o != nil && o.SucceededObjects.IsSet() {
		return true
	}

	return false
}

// SetSucceededObjects gets a reference to the given NullableInt32 and assigns it to the SucceededObjects field.
func (o *JobResponse) SetSucceededObjects(v int32) {
	o.SucceededObjects.Set(&v)
}
// SetSucceededObjectsNil sets the value for SucceededObjects to be an explicit nil
func (o *JobResponse) SetSucceededObjectsNil() {
	o.SucceededObjects.Set(nil)
}

// UnsetSucceededObjects ensures that no value is present for SucceededObjects, not even an explicit nil
func (o *JobResponse) UnsetSucceededObjects() {
	o.SucceededObjects.Unset()
}

// GetFailedObjects returns the FailedObjects field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobResponse) GetFailedObjects() int32 {
	if o == nil || IsNil(o.FailedObjects.Get()) {
		var ret int32
		return ret
	}
	return *o.FailedObjects.Get()
}

// GetFailedObjectsOk returns a tuple with the FailedObjects field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobResponse) GetFailedObjectsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.FailedObjects.Get(), o.FailedObjects.IsSet()
}

// HasFailedObjects returns a boolean if a field has been set.
func (o *JobResponse) HasFailedObjects() bool {
	if o != nil && o.FailedObjects.IsSet() {
		return true
	}

	return false
}

// SetFailedObjects gets a reference to the given NullableInt32 and assigns it to the FailedObjects field.
func (o *JobResponse) SetFailedObjects(v int32) {
	o.FailedObjects.Set(&v)
}
// SetFailedObjectsNil sets the value for FailedObjects to be an explicit nil
func (o *JobResponse) SetFailedObjectsNil() {
	o.FailedObjects.Set(nil)
}

// UnsetFailedObjects ensures that no value is present for FailedObjects, not even an explicit nil
func (o *JobResponse) UnsetFailedObjects() {
	o.FailedObjects.Unset()
}

// GetCancelledObjects returns the CancelledObjects field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobResponse) GetCancelledObjects() int32 {
	if o == nil || IsNil(o.CancelledObjects.Get()) {
		var ret int32
		return ret
	}
	return *o.CancelledObjects.Get()
}

// GetCancelledObjectsOk returns a tuple with the CancelledObjects field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobResponse) GetCancelledObjectsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CancelledObjects.Get(), o.CancelledObjects.IsSet()
}

// HasCancelledObjects returns a boolean if a field has been set.
func (o *JobResponse) HasCancelledObjects() bool {
	if o != nil && o.CancelledObjects.IsSet() {
		return true
	}

	return false
}

// SetCancelledObjects gets a reference to the given NullableInt32 and assigns it to the CancelledObjects field.
func (o *JobResponse) SetCancelledObjects(v int32) {
	o.CancelledObjects.Set(&v)
}
// SetCancelledObjectsNil sets the value for CancelledObjects to be an explicit nil
func (o *JobResponse) SetCancelledObjectsNil() {
	o.CancelledObjects.Set(nil)
}

// UnsetCancelledObjects ensures that no value is present for CancelledObjects, not even an explicit nil
func (o *JobResponse) UnsetCancelledObjects() {
	o.CancelledObjects.Unset()
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobResponse) GetStartedAt() string {
	if o == nil || IsNil(o.StartedAt.Get()) {
		var ret string
		return ret
	}
	return *o.StartedAt.Get()
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobResponse) GetStartedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartedAt.Get(), o.StartedAt.IsSet()
}

// HasStartedAt returns a boolean if a field has been set.
func (o *JobResponse) HasStartedAt() bool {
	if o != nil && o.StartedAt.IsSet() {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given NullableString and assigns it to the StartedAt field.
func (o *JobResponse) SetStartedAt(v string) {
	o.StartedAt.Set(&v)
}
// SetStartedAtNil sets the value for StartedAt to be an explicit nil
func (o *JobResponse) SetStartedAtNil() {
	o.StartedAt.Set(nil)
}

// UnsetStartedAt ensures that no value is present for StartedAt, not even an explicit nil
func (o *JobResponse) UnsetStartedAt() {
	o.StartedAt.Unset()
}

// GetFinishedAt returns the FinishedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobResponse) GetFinishedAt() string {
	if o == nil || IsNil(o.FinishedAt.Get()) {
		var ret string
		return ret
	}
	return *o.FinishedAt.Get()
}

// GetFinishedAtOk returns a tuple with the FinishedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobResponse) GetFinishedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FinishedAt.Get(), o.FinishedAt.IsSet()
}

// HasFinishedAt returns a boolean if a field has been set.
func (o *JobResponse) HasFinishedAt() bool {
	if o != nil && o.FinishedAt.IsSet() {
		return true
	}

	return false
}

// SetFinishedAt gets a reference to the given NullableString and assigns it to the FinishedAt field.
func (o *JobResponse) SetFinishedAt(v string) {
	o.FinishedAt.Set(&v)
}
// SetFinishedAtNil sets the value for FinishedAt to be an explicit nil
func (o *JobResponse) SetFinishedAtNil() {
	o.FinishedAt.Set(nil)
}

// UnsetFinishedAt ensures that no value is present for FinishedAt, not even an explicit nil
func (o *JobResponse) UnsetFinishedAt() {
	o.FinishedAt.Unset()
}

func (o JobResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	if o.OpKind.IsSet() {
		toSerialize["op_kind"] = o.OpKind.Get()
	}
	if o.Trigger.IsSet() {
		toSerialize["trigger"] = o.Trigger.Get()
	}
	if o.Error.IsSet() {
		toSerialize["error"] = o.Error.Get()
	}
	if o.TotalObjects.IsSet() {
		toSerialize["total_objects"] = o.TotalObjects.Get()
	}
	if o.SucceededObjects.IsSet() {
		toSerialize["succeeded_objects"] = o.SucceededObjects.Get()
	}
	if o.FailedObjects.IsSet() {
		toSerialize["failed_objects"] = o.FailedObjects.Get()
	}
	if o.CancelledObjects.IsSet() {
		toSerialize["cancelled_objects"] = o.CancelledObjects.Get()
	}
	if o.StartedAt.IsSet() {
		toSerialize["started_at"] = o.StartedAt.Get()
	}
	if o.FinishedAt.IsSet() {
		toSerialize["finished_at"] = o.FinishedAt.Get()
	}
	return toSerialize, nil
}

func (o *JobResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJobResponse := _JobResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJobResponse)

	if err != nil {
		return err
	}

	*o = JobResponse(varJobResponse)

	return err
}

type NullableJobResponse struct {
	value *JobResponse
	isSet bool
}

func (v NullableJobResponse) Get() *JobResponse {
	return v.value
}

func (v *NullableJobResponse) Set(val *JobResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableJobResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableJobResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobResponse(val *JobResponse) *NullableJobResponse {
	return &NullableJobResponse{value: val, isSet: true}
}

func (v NullableJobResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


