/*
MFS

Multi-source File-like Search — HTTP /v1 control plane.

API version: 0.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mfssdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddResponse{}

// AddResponse struct for AddResponse
type AddResponse struct {
	// sync job id; poll GET /v1/jobs/{job_id}
	JobId string `json:"job_id"`
}

type _AddResponse AddResponse

// NewAddResponse instantiates a new AddResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddResponse(jobId string) *AddResponse {
	this := AddResponse{}
	this.JobId = jobId
	return &this
}

// NewAddResponseWithDefaults instantiates a new AddResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddResponseWithDefaults() *AddResponse {
	this := AddResponse{}
	return &this
}

// GetJobId returns the JobId field value
func (o *AddResponse) GetJobId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value
// and a boolean to check if the value has been set.
func (o *AddResponse) GetJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobId, true
}

// SetJobId sets field value
func (o *AddResponse) SetJobId(v string) {
	o.JobId = v
}

func (o AddResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["job_id"] = o.JobId
	return toSerialize, nil
}

func (o *AddResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"job_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddResponse := _AddResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddResponse)

	if err != nil {
		return err
	}

	*o = AddResponse(varAddResponse)

	return err
}

type NullableAddResponse struct {
	value *AddResponse
	isSet bool
}

func (v NullableAddResponse) Get() *AddResponse {
	return v.value
}

func (v *NullableAddResponse) Set(val *AddResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAddResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAddResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddResponse(val *AddResponse) *NullableAddResponse {
	return &NullableAddResponse{value: val, isSet: true}
}

func (v NullableAddResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


