/*
MFS

Multi-source File-like Search — HTTP /v1 control plane.

API version: 0.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mfssdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatusResponse{}

// StatusResponse struct for StatusResponse
type StatusResponse struct {
	Connectors []ConnectorRow `json:"connectors"`
	// count of jobs by status
	Jobs map[string]int32 `json:"jobs,omitempty"`
}

type _StatusResponse StatusResponse

// NewStatusResponse instantiates a new StatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatusResponse(connectors []ConnectorRow) *StatusResponse {
	this := StatusResponse{}
	this.Connectors = connectors
	return &this
}

// NewStatusResponseWithDefaults instantiates a new StatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatusResponseWithDefaults() *StatusResponse {
	this := StatusResponse{}
	return &this
}

// GetConnectors returns the Connectors field value
func (o *StatusResponse) GetConnectors() []ConnectorRow {
	if o == nil {
		var ret []ConnectorRow
		return ret
	}

	return o.Connectors
}

// GetConnectorsOk returns a tuple with the Connectors field value
// and a boolean to check if the value has been set.
func (o *StatusResponse) GetConnectorsOk() ([]ConnectorRow, bool) {
	if o == nil {
		return nil, false
	}
	return o.Connectors, true
}

// SetConnectors sets field value
func (o *StatusResponse) SetConnectors(v []ConnectorRow) {
	o.Connectors = v
}

// GetJobs returns the Jobs field value if set, zero value otherwise.
func (o *StatusResponse) GetJobs() map[string]int32 {
	if o == nil || IsNil(o.Jobs) {
		var ret map[string]int32
		return ret
	}
	return o.Jobs
}

// GetJobsOk returns a tuple with the Jobs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatusResponse) GetJobsOk() (map[string]int32, bool) {
	if o == nil || IsNil(o.Jobs) {
		return map[string]int32{}, false
	}
	return o.Jobs, true
}

// HasJobs returns a boolean if a field has been set.
func (o *StatusResponse) HasJobs() bool {
	if o != nil && !IsNil(o.Jobs) {
		return true
	}

	return false
}

// SetJobs gets a reference to the given map[string]int32 and assigns it to the Jobs field.
func (o *StatusResponse) SetJobs(v map[string]int32) {
	o.Jobs = v
}

func (o StatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["connectors"] = o.Connectors
	if !IsNil(o.Jobs) {
		toSerialize["jobs"] = o.Jobs
	}
	return toSerialize, nil
}

func (o *StatusResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"connectors",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStatusResponse := _StatusResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStatusResponse)

	if err != nil {
		return err
	}

	*o = StatusResponse(varStatusResponse)

	return err
}

type NullableStatusResponse struct {
	value *StatusResponse
	isSet bool
}

func (v NullableStatusResponse) Get() *StatusResponse {
	return v.value
}

func (v *NullableStatusResponse) Set(val *StatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatusResponse(val *StatusResponse) *NullableStatusResponse {
	return &NullableStatusResponse{value: val, isSet: true}
}

func (v NullableStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


