"""Interactive per-connector add wizard — `mfs-server connector add <uri>`.

Distinct from `mfs-server setup` (which writes the server-level base config).
This wizard handles a single connector at a time: parse the scheme, walk the
fields declared in connector_schemas.SCHEMAS, write the resulting TOML to
$MFS_HOME/connectors/<alias>.toml, and (if a server is running locally) POST
to /v1/add so indexing kicks off immediately.

Design choices:

- One connector per invocation. The user picks the scheme by passing a URI
  (`mfs-server connector add postgres://prod-db`), not by walking a menu of
  20 schemes.
- Fields are declarative in connector_schemas. Add a new connector → add
  its row there, the wizard picks it up automatically.
- Secrets stay on disk in the connector TOML; the wizard never echoes them
  back. The TOML lives next to the server (server-side, not pushed
  upstream).
- HTTP registration is best-effort: if `/v1/server/info` doesn't respond,
  the TOML is still written and the user is told to start the server.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

from ..config import mfs_home
from .connector_schemas import ConnectorField, ConnectorSchema, lookup_schema, supported_schemes


# ─── prompt helpers (mirror setup_wizard so the two flows feel the same) ────


def _prompt(label: str, default: str = "", *, secret: bool = False) -> str:
    suffix = f" [{default}]" if default else ""
    if secret:
        suffix += " (input hidden)"
    try:
        raw = input(f"  {label}{suffix}: ")
    except EOFError:
        # stdin closed (piped input ran out, or Ctrl-D on a real terminal).
        # Treat as Ctrl-C so the runner aborts cleanly without saving.
        raise KeyboardInterrupt from None
    val = raw.strip()
    return val if val else default


def _prompt_choice(label: str, choices: list[str], default: str) -> str:
    options = "/".join(c + ("*" if c == default else "") for c in choices)
    while True:
        val = _prompt(f"{label} ({options})", default).lower()
        if val in choices:
            return val
        print(f"    ! please choose one of: {', '.join(choices)}")


def _prompt_field(f: ConnectorField) -> Any:
    if f.help:
        print(f"    ({f.help})")
    while True:
        raw = _prompt(f.label, f.default, secret=f.secret)
        if not raw:
            if f.required:
                print(f"    ! {f.name} is required")
                continue
            return None
        # Coerce
        try:
            if f.multi:
                items = [s.strip() for s in raw.split(",") if s.strip()]
                if f.type == "int":
                    return [int(x) for x in items]
                return items
            if f.type == "int":
                return int(raw)
            if f.type == "bool":
                return raw.lower() in ("y", "yes", "true", "1", "on")
            return raw
        except ValueError as e:
            print(f"    ! could not parse value: {e}")


# ─── alias derivation ──────────────────────────────────────────────────────


def _derive_alias(uri: str) -> str:
    """`postgres://prod-db` -> 'prod-db', `slack://acme` -> 'acme', etc.

    For URIs without a clear host slug we fall back to the scheme — the user
    can rename the resulting TOML by hand if they care.
    """
    try:
        parsed = urlparse(uri)
        candidate = (parsed.netloc or parsed.path or "").strip("/")
        # github://owner/repo -> 'owner-repo'
        candidate = candidate.replace("/", "-").replace(":", "-")
        return candidate or parsed.scheme
    except Exception:  # noqa: BLE001
        return uri.split("://", 1)[0]


# ─── TOML rendering (small subset — shared with setup_wizard) ──────────────


def _format_scalar(v: Any) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, list):
        return "[" + ", ".join(_format_scalar(x) for x in v) + "]"
    s = str(v).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{s}"'


def _render_toml(
    scheme: str,
    uri: str,
    fields: dict[str, Any],
    extras_hint: str,
    *,
    objects: list[dict[str, Any]] | None = None,
) -> str:
    lines = [
        f"# mfs-server connector config — {scheme}",
        f"# URI: {uri}",
        "#",
        "# Generated by `mfs-server connector add`. You can hand-edit this file and",
        "# re-run `mfs-server connector add <uri>` (or `mfs add <uri> --update`) to",
        "# apply changes; secrets are stored in plaintext here, so chmod 0600 the",
        "# enclosing directory.",
    ]
    if extras_hint:
        lines.append("#")
        for ln in extras_hint.strip().splitlines():
            lines.append(f"# {ln}")
    lines.append("")
    for k, v in fields.items():
        lines.append(f"{k} = {_format_scalar(v)}")
    # Per-object blocks: text_fields + locator_fields, one [[objects]] per table.
    for obj in objects or []:
        lines.append("")
        lines.append("[[objects]]")
        for k, v in obj.items():
            lines.append(f"{k} = {_format_scalar(v)}")
    lines.append("")
    return "\n".join(lines)


# ─── introspection + per-table prompt ──────────────────────────────────────


class _IntrospectError(Exception):
    """Wraps non-KeyboardInterrupt failures (auth, network, missing tables, ...)
    from connect() / introspect_for_wizard() so the runner can keep going with
    no [[objects]] blocks rather than abort."""


class _StubStateStore:
    """No-op StateStore for the wizard. introspect_for_wizard() doesn't touch
    state, but ConnectorPlugin.__init__ requires one."""

    async def get(self, key: str) -> Any:
        return None

    async def set(self, key: str, value: Any) -> None:
        return None

    async def delete(self, key: str) -> None:
        return None

    async def checkpoint(self) -> None:
        return None


def _introspect_and_prompt(scheme: str, uri: str, values: dict[str, Any]) -> list[dict[str, Any]]:
    """Connect to the source with the just-collected creds, walk its tables /
    collections, and prompt the user to confirm text_fields / locator_fields
    per object. Returns a list of dicts ready to be rendered as `[[objects]]`
    blocks. Returns [] if the scheme doesn't implement introspect.
    """
    import asyncio

    from ..connectors.base import ConnectorContext
    from ..connectors.registry import get_plugin_cls, load_builtin

    load_builtin()
    plugin_cls = get_plugin_cls(scheme)
    if plugin_cls is None:
        return []

    # Build a plugin instance with the wizard-collected values as config dict.
    # SQL plugins read via self._cfg() so a plain dict works. credential is
    # passed as None — secrets sit in the config dict directly.
    state = _StubStateStore()
    ctx = ConnectorContext(state, connector_id="wizard", namespace_id="default")
    try:
        plugin = plugin_cls(config=dict(values), credential=None, ctx=ctx)
    except Exception as e:  # noqa: BLE001
        raise _IntrospectError(f"plugin instantiation failed: {e}") from e

    async def go() -> dict[str, dict]:
        try:
            await plugin.connect()
        except Exception as e:  # noqa: BLE001
            raise _IntrospectError(f"connect failed (check credentials?): {e}") from e
        try:
            return await plugin.introspect_for_wizard()
        finally:
            with contextlib.suppress(Exception):
                await plugin.close()

    import contextlib

    print()
    print(f"── live introspection: {uri} ──")
    print("   Connecting + listing tables / collections …")
    try:
        introspect = asyncio.run(go())
    except _IntrospectError:
        raise
    except Exception as e:  # noqa: BLE001
        raise _IntrospectError(str(e)) from e

    if not introspect:
        # Non-SQL connectors or empty source — nothing to prompt about.
        print(
            "   (no tables / collections to configure — the connector either doesn't\n"
            "   support introspection or the source is empty.)"
        )
        return []

    print(f"   Found {len(introspect)} object(s). For each one you can index it as-is,")
    print("   tweak its text_fields / locator_fields, or skip it entirely.")
    return _prompt_per_object(introspect)


def _prompt_per_object(introspect: dict[str, dict]) -> list[dict[str, Any]]:
    """Walk the introspect output and ask the user about each table.

    UX:
    - shows table path + column count + suggested text_fields + suggested PK
    - "use suggestions" (y, default) → take both defaults
    - "edit" (e)                     → prompt text_fields + locator_fields lines
    - "skip" (s)                     → don't emit an [[objects]] block (won't index)
    """
    objects: list[dict[str, Any]] = []
    for path, info in introspect.items():
        cols = info.get("columns", [])
        pk = info.get("pk", [])
        text_default = info.get("text_candidates", [])
        # Some tables have no text columns at all (pure-numeric metric tables);
        # skip them by default — text_fields = [] would index zero content.
        if not text_default and not cols:
            print(f"\n  {path}: empty schema → skipping")
            continue
        col_summary = ", ".join(
            f"{c['name']}({c['type']})" + ("*" if c.get("pk") else "") for c in cols[:8]
        )
        if len(cols) > 8:
            col_summary += f", …(+{len(cols) - 8} more)"

        print(f"\n  {path}")
        print(f"    columns:        {col_summary or '(none discovered)'}")
        print(f"    suggested text: {text_default or '(none — table has no string cols)'}")
        print(f"    suggested PK:   {pk or '(none — set locator_fields manually)'}")
        choice = _prompt_choice(
            "index this table?",
            ["use", "edit", "skip"],
            "use" if text_default else "skip",
        )
        if choice == "skip":
            continue
        if choice == "use":
            text_fields = list(text_default)
            locator_fields = list(pk)
        else:  # edit
            raw_t = _prompt(
                "text_fields (comma-separated)",
                ",".join(text_default),
            )
            raw_l = _prompt(
                "locator_fields (comma-separated)",
                ",".join(pk),
            )
            text_fields = [s.strip() for s in raw_t.split(",") if s.strip()]
            locator_fields = [s.strip() for s in raw_l.split(",") if s.strip()]
        if not text_fields:
            print("    (text_fields empty — this table would index zero content; skipping)")
            continue
        block: dict[str, Any] = {"match": path, "text_fields": text_fields}
        if locator_fields:
            block["locator_fields"] = locator_fields
        objects.append(block)
    return objects


# ─── HTTP registration via local /v1/add ────────────────────────────────────


def _post_add(uri: str, config_toml: str, server_port: int = 13619) -> tuple[bool, str]:
    """Best-effort POST /v1/add against the local server.

    Returns (ok, message). If the server is unreachable we don't treat that
    as a wizard failure — the user can start the server later and the TOML
    is already on disk.
    """
    import urllib.error
    import urllib.request

    # API token: env wins, else the file the server writes on first run.
    token = os.environ.get("MFS_API_TOKEN")
    if not token:
        token_file = mfs_home() / "server.token"
        if token_file.exists():
            token = token_file.read_text().strip()
    headers = {"Content-Type": "application/json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"

    payload = json.dumps({"target": uri, "config": config_toml}).encode()
    req = urllib.request.Request(
        f"http://127.0.0.1:{server_port}/v1/add",
        data=payload,
        method="POST",
        headers=headers,
    )
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            body = resp.read().decode()
            try:
                parsed = json.loads(body)
                return True, f"job_id={parsed.get('job_id')}"
            except json.JSONDecodeError:
                return True, body
    except urllib.error.HTTPError as e:
        return False, f"server returned {e.code}: {e.read().decode()[:200]}"
    except (urllib.error.URLError, ConnectionRefusedError, TimeoutError) as e:
        return False, f"server unreachable ({e})"


# ─── runner ─────────────────────────────────────────────────────────────────


def run_connector_add(
    uri: str,
    *,
    no_sync: bool = False,
    out_dir: Path | None = None,
    server_port: int = 13619,
) -> int:
    parsed = urlparse(uri)
    scheme = parsed.scheme
    if not scheme:
        print(f"error: target '{uri}' is missing a scheme", file=sys.stderr)
        print(f"       supported: {', '.join(supported_schemes())}", file=sys.stderr)
        return 2

    if scheme == "file":
        print(
            "file:// connectors don't need a wizard — just `mfs add ./your/path`.\n"
            "If you want a custom alias: `mfs add file://my-alias /abs/path`.",
            file=sys.stderr,
        )
        return 2

    schema: ConnectorSchema | None = lookup_schema(scheme)
    if not schema:
        print(f"error: no interactive schema for scheme '{scheme}'", file=sys.stderr)
        print(f"       supported: {', '.join(supported_schemes())}", file=sys.stderr)
        print(
            "       (use `mfs add <uri> --config /path/to/config.toml` directly "
            "for unsupported schemes)",
            file=sys.stderr,
        )
        return 2

    out_dir = out_dir or (mfs_home() / "connectors")
    out_dir.mkdir(parents=True, exist_ok=True)
    alias = _derive_alias(uri)
    out_path = out_dir / f"{alias}.toml"

    print()
    print(f"── mfs-server connector add: {scheme} ──")
    print(f"   {schema.summary}")
    print(f"   URI:        {uri}")
    print(f"   Writing to: {out_path}")
    if out_path.exists():
        print("   (existing file will be backed up to .bak before overwriting)")
    print("   Press Enter to accept defaults. Ctrl-C aborts without saving.")
    print()

    try:
        values: dict[str, Any] = {}
        for f in schema.fields:
            v = _prompt_field(f)
            if v is not None:
                values[f.name] = v
    except KeyboardInterrupt:
        print("\naborted; nothing written.")
        return 130

    # Per-table introspection (SQL-family connectors only). connect() doubles
    # as a credential healthcheck: if the credentials are bad we surface it
    # here, before writing the TOML or hitting /v1/add.
    objects: list[dict[str, Any]] = []
    try:
        objects = _introspect_and_prompt(scheme, uri, values)
    except KeyboardInterrupt:
        print("\naborted; nothing written.")
        return 130
    except _IntrospectError as e:
        print(f"\n  ! could not introspect schema: {e}")
        print("  (writing the connector TOML without [[objects]] blocks; you can")
        print("   add them by hand later — see the connector reference docs.)")

    rendered = _render_toml(scheme, uri, values, schema.extras_hint, objects=objects)

    if out_path.exists():
        bak = out_path.with_suffix(out_path.suffix + ".bak")
        bak.write_bytes(out_path.read_bytes())
        print(f"\nbacked up previous config to {bak}")
    out_path.write_text(rendered)
    try:
        out_path.chmod(0o600)
    except OSError:
        pass
    print(f"wrote {out_path}")

    if no_sync:
        print(
            f"\n--no-sync set; skipping server registration.\n"
            f"To register later: `mfs add {uri} --config {out_path}`."
        )
        return 0

    print("\nregistering against the local server …")
    ok, msg = _post_add(uri, rendered, server_port=server_port)
    if ok:
        print(f"  ok: {msg}")
        print(f"\nWatch progress: `mfs status {uri}`\nList jobs:      `mfs job ls`")
        return 0

    # Server unreachable / errored — still successful from the wizard's POV
    # (TOML is on disk); just tell the user how to finish manually.
    print(f"  could not register against local server: {msg}")
    print(
        f"\nTOML is saved. To register later (after starting the server):\n"
        f"  mfs add {uri} --config {out_path}"
    )
    return 0


def main_entry(argv: list[str]) -> int:
    """argparse-friendly entry. argv is the args AFTER `connector add`."""
    import argparse

    p = argparse.ArgumentParser(
        prog="mfs-server connector add",
        description="Interactive wizard for adding a connector.",
    )
    p.add_argument("uri", help=f"Connector URI (one of: {', '.join(supported_schemes())})")
    p.add_argument(
        "--no-sync",
        action="store_true",
        help="Write the TOML but don't POST /v1/add (skip immediate registration)",
    )
    p.add_argument(
        "--out-dir",
        type=Path,
        default=None,
        help="Where to write the connector TOML (default: $MFS_HOME/connectors/)",
    )
    p.add_argument(
        "--server-port",
        type=int,
        default=13619,
        help="Port the local mfs-server listens on (default: 13619)",
    )
    args = p.parse_args(argv)
    return run_connector_add(
        args.uri,
        no_sync=args.no_sync,
        out_dir=args.out_dir,
        server_port=args.server_port,
    )
