"""Interactive per-connector add wizard — `mfs-server connector add <uri>`.

Distinct from `mfs-server setup` (which writes the server-level base config).
This wizard handles a single connector at a time: parse the scheme, walk the
fields declared in connector_schemas.SCHEMAS, write the resulting TOML to
$MFS_HOME/connectors/<alias>.toml, and (if a server is running locally) POST
to /v1/add so indexing kicks off immediately.

Design choices:

- One connector per invocation. The user picks the scheme by passing a URI
  (`mfs-server connector add postgres://prod-db`), not by walking a menu of
  20 schemes.
- Fields are declarative in connector_schemas. Add a new connector → add
  its row there, the wizard picks it up automatically.
- Secrets stay on disk in the connector TOML; the wizard never echoes them
  back. The TOML lives next to the server (server-side, not pushed
  upstream).
- HTTP registration is best-effort: if `/v1/server/info` doesn't respond,
  the TOML is still written and the user is told to start the server.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

from ..config import mfs_home
from .connector_schemas import ConnectorField, ConnectorSchema, lookup_schema, supported_schemes


# ─── prompt helpers (mirror setup_wizard so the two flows feel the same) ────


def _prompt(label: str, default: str = "", *, secret: bool = False) -> str:
    suffix = f" [{default}]" if default else ""
    if secret:
        suffix += " (input hidden)"
    try:
        raw = input(f"  {label}{suffix}: ")
    except EOFError:
        # stdin closed (piped input ran out, or Ctrl-D on a real terminal).
        # Treat as Ctrl-C so the runner aborts cleanly without saving.
        raise KeyboardInterrupt from None
    val = raw.strip()
    return val if val else default


def _prompt_field(f: ConnectorField) -> Any:
    if f.help:
        print(f"    ({f.help})")
    while True:
        raw = _prompt(f.label, f.default, secret=f.secret)
        if not raw:
            if f.required:
                print(f"    ! {f.name} is required")
                continue
            return None
        # Coerce
        try:
            if f.multi:
                items = [s.strip() for s in raw.split(",") if s.strip()]
                if f.type == "int":
                    return [int(x) for x in items]
                return items
            if f.type == "int":
                return int(raw)
            if f.type == "bool":
                return raw.lower() in ("y", "yes", "true", "1", "on")
            return raw
        except ValueError as e:
            print(f"    ! could not parse value: {e}")


# ─── alias derivation ──────────────────────────────────────────────────────


def _derive_alias(uri: str) -> str:
    """`postgres://prod-db` -> 'prod-db', `slack://acme` -> 'acme', etc.

    For URIs without a clear host slug we fall back to the scheme — the user
    can rename the resulting TOML by hand if they care.
    """
    try:
        parsed = urlparse(uri)
        candidate = (parsed.netloc or parsed.path or "").strip("/")
        # github://owner/repo -> 'owner-repo'
        candidate = candidate.replace("/", "-").replace(":", "-")
        return candidate or parsed.scheme
    except Exception:  # noqa: BLE001
        return uri.split("://", 1)[0]


# ─── TOML rendering (small subset — shared with setup_wizard) ──────────────


def _format_scalar(v: Any) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, list):
        return "[" + ", ".join(_format_scalar(x) for x in v) + "]"
    s = str(v).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{s}"'


def _render_toml(scheme: str, uri: str, fields: dict[str, Any], extras_hint: str) -> str:
    lines = [
        f"# mfs-server connector config — {scheme}",
        f"# URI: {uri}",
        "#",
        "# Generated by `mfs-server connector add`. You can hand-edit this file and",
        "# re-run `mfs-server connector add <uri>` (or `mfs add <uri> --update`) to",
        "# apply changes; secrets are stored in plaintext here, so chmod 0600 the",
        "# enclosing directory.",
    ]
    if extras_hint:
        lines.append("#")
        for ln in extras_hint.strip().splitlines():
            lines.append(f"# {ln}")
    lines.append("")
    for k, v in fields.items():
        lines.append(f"{k} = {_format_scalar(v)}")
    lines.append("")
    return "\n".join(lines)


# ─── HTTP registration via local /v1/add ────────────────────────────────────


def _post_add(uri: str, config_toml: str, server_port: int = 13619) -> tuple[bool, str]:
    """Best-effort POST /v1/add against the local server.

    Returns (ok, message). If the server is unreachable we don't treat that
    as a wizard failure — the user can start the server later and the TOML
    is already on disk.
    """
    import urllib.error
    import urllib.request

    # API token: env wins, else the file the server writes on first run.
    token = os.environ.get("MFS_API_TOKEN")
    if not token:
        token_file = mfs_home() / "server.token"
        if token_file.exists():
            token = token_file.read_text().strip()
    headers = {"Content-Type": "application/json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"

    payload = json.dumps({"target": uri, "config": config_toml}).encode()
    req = urllib.request.Request(
        f"http://127.0.0.1:{server_port}/v1/add",
        data=payload,
        method="POST",
        headers=headers,
    )
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            body = resp.read().decode()
            try:
                parsed = json.loads(body)
                return True, f"job_id={parsed.get('job_id')}"
            except json.JSONDecodeError:
                return True, body
    except urllib.error.HTTPError as e:
        return False, f"server returned {e.code}: {e.read().decode()[:200]}"
    except (urllib.error.URLError, ConnectionRefusedError, TimeoutError) as e:
        return False, f"server unreachable ({e})"


# ─── runner ─────────────────────────────────────────────────────────────────


def run_connector_add(
    uri: str,
    *,
    no_sync: bool = False,
    out_dir: Path | None = None,
    server_port: int = 13619,
) -> int:
    parsed = urlparse(uri)
    scheme = parsed.scheme
    if not scheme:
        print(f"error: target '{uri}' is missing a scheme", file=sys.stderr)
        print(f"       supported: {', '.join(supported_schemes())}", file=sys.stderr)
        return 2

    if scheme == "file":
        print(
            "file:// connectors don't need a wizard — just `mfs add ./your/path`.\n"
            "If you want a custom alias: `mfs add file://my-alias /abs/path`.",
            file=sys.stderr,
        )
        return 2

    schema: ConnectorSchema | None = lookup_schema(scheme)
    if not schema:
        print(f"error: no interactive schema for scheme '{scheme}'", file=sys.stderr)
        print(f"       supported: {', '.join(supported_schemes())}", file=sys.stderr)
        print(
            "       (use `mfs add <uri> --config /path/to/config.toml` directly "
            "for unsupported schemes)",
            file=sys.stderr,
        )
        return 2

    out_dir = out_dir or (mfs_home() / "connectors")
    out_dir.mkdir(parents=True, exist_ok=True)
    alias = _derive_alias(uri)
    out_path = out_dir / f"{alias}.toml"

    print()
    print(f"── mfs-server connector add: {scheme} ──")
    print(f"   {schema.summary}")
    print(f"   URI:        {uri}")
    print(f"   Writing to: {out_path}")
    if out_path.exists():
        print("   (existing file will be backed up to .bak before overwriting)")
    print("   Press Enter to accept defaults. Ctrl-C aborts without saving.")
    print()

    try:
        values: dict[str, Any] = {}
        for f in schema.fields:
            v = _prompt_field(f)
            if v is not None:
                values[f.name] = v
    except KeyboardInterrupt:
        print("\naborted; nothing written.")
        return 130

    rendered = _render_toml(scheme, uri, values, schema.extras_hint)

    if out_path.exists():
        bak = out_path.with_suffix(out_path.suffix + ".bak")
        bak.write_bytes(out_path.read_bytes())
        print(f"\nbacked up previous config to {bak}")
    out_path.write_text(rendered)
    try:
        out_path.chmod(0o600)
    except OSError:
        pass
    print(f"wrote {out_path}")

    if no_sync:
        print(
            f"\n--no-sync set; skipping server registration.\n"
            f"To register later: `mfs add {uri} --config {out_path}`."
        )
        return 0

    print("\nregistering against the local server …")
    ok, msg = _post_add(uri, rendered, server_port=server_port)
    if ok:
        print(f"  ok: {msg}")
        print(f"\nWatch progress: `mfs status {uri}`\nList jobs:      `mfs job ls`")
        return 0

    # Server unreachable / errored — still successful from the wizard's POV
    # (TOML is on disk); just tell the user how to finish manually.
    print(f"  could not register against local server: {msg}")
    print(
        f"\nTOML is saved. To register later (after starting the server):\n"
        f"  mfs add {uri} --config {out_path}"
    )
    return 0


def main_entry(argv: list[str]) -> int:
    """argparse-friendly entry. argv is the args AFTER `connector add`."""
    import argparse

    p = argparse.ArgumentParser(
        prog="mfs-server connector add",
        description="Interactive wizard for adding a connector.",
    )
    p.add_argument("uri", help=f"Connector URI (one of: {', '.join(supported_schemes())})")
    p.add_argument(
        "--no-sync",
        action="store_true",
        help="Write the TOML but don't POST /v1/add (skip immediate registration)",
    )
    p.add_argument(
        "--out-dir",
        type=Path,
        default=None,
        help="Where to write the connector TOML (default: $MFS_HOME/connectors/)",
    )
    p.add_argument(
        "--server-port",
        type=int,
        default=13619,
        help="Port the local mfs-server listens on (default: 13619)",
    )
    args = p.parse_args(argv)
    return run_connector_add(
        args.uri,
        no_sync=args.no_sync,
        out_dir=args.out_dir,
        server_port=args.server_port,
    )
